"""charging_sessions__and__transactions

Revision ID: 0004
Revises: 0003
Create Date: 2023-09-10 09:28:55.994776

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.schema import Sequence, CreateSequence


# revision identifiers, used by Alembic.
revision = '0004'
down_revision = '0003'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(CreateSequence(Sequence('transaction_id_seq')))
    op.create_table('transactions',
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('vehicle', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('meter_start', sa.Integer(), nullable=False),
    sa.Column('meter_stop', sa.Integer(), nullable=True),
    sa.Column('charge_point', sa.String(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), server_default=sa.text("nextval('transaction_id_seq')"), nullable=True),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_table('transactions')
    # ### end Alembic commands ###
